# Generated by Django 6.1 on 2026-09-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='categoria',
            field=models.CharField(choices=[('000', '000 – Generalidades e Informação')], default='000', max_length=3),
        ),
        migrations.AddField(
            model_name='livro',
            name='tipo_acervo',
            field=models.CharField(choices=[('DIGITAL', 'Digital'), ('FISICO', 'Físico')], default='FISICO', max_length=10),
        ),
    ]
