# Generated by Django 6.1 on 2026-09-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0002_livro_categoria_livro_tipo_acervo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='categoria',
            field=models.CharField(choices=[('000', '000 – Generalidades e Informação'), ('100', '100 – Filosofia e Psicologia')], default='000', max_length=3),
        ),
    ]
